version: '3.8'
services:
services:
  reef-backend:
    image: registry.relizahub.com/library/reef-backend
    environment:
     - POSTGRES_HOST=reef-postgresql
     - POSTGRES_PORT=5432
    depends_on:
     - reef-postgresql
    ports:
     - "4002:4001"
    volumes:
      - "tfspace-data-registry:/app/tf_space"
  reef-ui:
    image: registry.relizahub.com/library/reef-ui
    ports:
     - "8112:80"
    environment:
     - BACKEND_HOST=reef-backend
     - BACKEND_PORT=4001
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
     - reef-backend
  reef-postgres-init:
    image: 'flyway/flyway:9-alpine'
    restart: on-failure
    depends_on:
      - reef-postgresql
    command:
      [
        '-url=jdbc:postgresql://reef-postgresql:5432/postgres',
        '-user=postgres',
        '-password=password',
        '-defaultSchema=reef',
        '-schemas=reef',
        'migrate'
      ]
    volumes:
      - ../../backend/migrations:/flyway/sql
  reef-postgresql:
    image: postgres:16
    environment:
     - POSTGRES_PASSWORD=password
    volumes:
      - "pg-data-registry:/var/lib/postgresql/data"
volumes:
  pg-data-registry:
    driver: local
  tfspace-data-registry:
    driver: local