export default {
    AWS_ACCOUNT_PROVIDER: "AWS",
    AZURE_ACCOUNT_PROVIDER: "AZURE",
    GIT_ACCOUNT_PROVIDER: "GIT",
    GITHUB_REPOSITORY_VENDOR: "GITHUB",
    STATUS_ACTIVE: "ACTIVE",
    STATUS_ARCHIVED: "ARCHIVED",
    STATUS_PENDING: "PENDING",
    TF_DEFAULT_TFVARS_FILE: "terraform.tfvars.json",
    SILO_PREFIX: "silo-",
    INSTANCE_PREFIX: "instance-",
    GIT_PREFIX: "git-",
    CRED_PREFIX: "cred-",
    TF_SPACE: "tf_space",
    CREATE_OPERATION: "create",
    DESTROY_OPERATION: "destroy"
}