apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reef.labels" . | nindent 4 }}
spec:
  selector:
    app: reef
    name: reef-backend
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001